[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = [
  "npm ci",
  "npm run prisma:generate"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run prisma:generate && npm run prisma:db:push --accept-data-loss && npm run start:prod"
