[phases.setup]
nixPkgs = ["nodejs-20_x", "postgresql"]

[phases.install]
cmds = [
  "cd vite-frontend && npm ci",
  "cd backend && npm ci",
  "cd backend && npm run prisma:generate"
]

[phases.build]
cmds = [
  "cd vite-frontend && npm run build",
  "mkdir -p backend/public",
  "cp -r vite-frontend/dist/* backend/public/",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm run prisma:generate && npm run prisma:db:push --accept-data-loss && npm run start:prod"
